-- MySQL Script generated by MySQL Workbench
-- Thu Feb 27 14:07:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Trabalho_Seguro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Trabalho_Seguro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Trabalho_Seguro` DEFAULT CHARACTER SET utf8 ;
USE `Trabalho_Seguro` ;

-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `posicao` VARCHAR(45) NULL,
  `nome_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Setor` (
  `idSetor` INT NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSetor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Funcionario` (
  `id_funcionario` INT NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `formacao` VARCHAR(45) NOT NULL,
  `nome_funcionario` VARCHAR(45) NOT NULL,
  `sobrenome_funcionario` VARCHAR(45) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `ddd` VARCHAR(4) NOT NULL,
  `numero` VARCHAR(14) NOT NULL,
  `ddd_emergencial` VARCHAR(4) NULL,
  `telefoneEmergencial` VARCHAR(14) NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(110) NOT NULL,
  `numero_residencia` VARCHAR(10) NOT NULL,
  `tempoTrabalho` VARCHAR(15) NOT NULL,
  `Cargo_idCargo1` INT NOT NULL,
  `Setor_idSetor` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_Funcionario_Cargo1_idx` (`Cargo_idCargo1` ),
  INDEX `fk_Funcionario_Setor1_idx` (`Setor_idSetor` ),
  CONSTRAINT `fk_Funcionario_Cargo1`
    FOREIGN KEY (`Cargo_idCargo1`)
    REFERENCES `Trabalho_Seguro`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Setor1`
    FOREIGN KEY (`Setor_idSetor`)
    REFERENCES `Trabalho_Seguro`.`Setor` (`idSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Funcao` (
  `idFuncao` INT NOT NULL AUTO_INCREMENT,
  `descricao_funcao` VARCHAR(45) NOT NULL,
  `Cargo_idCargo` INT NOT NULL,
  PRIMARY KEY (`idFuncao`),
  INDEX `fk_Funcao_Cargo1_idx` (`Cargo_idCargo` ),
  CONSTRAINT `fk_Funcao_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `Trabalho_Seguro`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Incidentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Incidentes` (
  `idIncidente` INT NOT NULL AUTO_INCREMENT,
  `dt_hr_incidente` DATETIME NOT NULL,
  `status_incidente` VARCHAR(30) NULL,
  `descricao_incidente` VARCHAR(100) NOT NULL,
  `local_incidente` VARCHAR(45) NOT NULL,
  `tipo_incidente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIncidente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`EPI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`EPI` (
  `idEPI` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `validade` DATE NOT NULL,
  PRIMARY KEY (`idEPI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Acidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Acidente` (
  `idAcidente` INT NOT NULL,
  `dt_hr_acidente` DATETIME NOT NULL,
  `status_acidente` VARCHAR(30) NULL,
  `descricao_acidente` VARCHAR(100) NOT NULL,
  `local_acidente` VARCHAR(45) NOT NULL,
  `tipo_acidente` VARCHAR(45) NOT NULL,
  `uso_epi_acidente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAcidente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Afeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Afeta` (
  `lesao` VARCHAR(45) NULL,
  `Funcionario_id_funcionario` INT NOT NULL,
  `Acidente_idAcidente` INT NOT NULL,
  PRIMARY KEY (`Funcionario_id_funcionario`, `Acidente_idAcidente`),
  INDEX `fk_Afeta_Acidente1_idx` (`Acidente_idAcidente` ),
  CONSTRAINT `fk_Afeta_Funcionario1`
    FOREIGN KEY (`Funcionario_id_funcionario`)
    REFERENCES `Trabalho_Seguro`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Afeta_Acidente1`
    FOREIGN KEY (`Acidente_idAcidente`)
    REFERENCES `Trabalho_Seguro`.`Acidente` (`idAcidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Desvio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Desvio` (
  `idDesvio` INT NOT NULL,
  `dt_hr_desvio` DATETIME NOT NULL,
  `status_desvio` VARCHAR(30) NULL,
  `descricao_desvio` TEXT(1000) NOT NULL,
  `local_desvio` VARCHAR(45) NOT NULL,
  `danos_desvio` VARCHAR(45) NOT NULL,
  `ala_desvio` VARCHAR(45) NOT NULL,
  `recomendacao_desvio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDesvio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Registra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Registra` (
  `Incidentes_idIncidentes` INT NOT NULL,
  `Acidente_idAcidente` INT NOT NULL,
  `Desvio_idDesvio` INT NOT NULL,
  `Funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`Incidentes_idIncidentes`, `Acidente_idAcidente`, `Desvio_idDesvio`, `Funcionario_id_funcionario`),
  INDEX `fk_Funcionario_has_Incidentes_Incidentes2_idx` (`Incidentes_idIncidentes` ),
  INDEX `fk_Registra_Acidente1_idx` (`Acidente_idAcidente` ),
  INDEX `fk_Registra_Desvio1_idx` (`Desvio_idDesvio` ),
  INDEX `fk_Registra_Funcionario1_idx` (`Funcionario_id_funcionario` ),
  CONSTRAINT `fk_Funcionario_has_Incidentes_Incidentes2`
    FOREIGN KEY (`Incidentes_idIncidentes`)
    REFERENCES `Trabalho_Seguro`.`Incidentes` (`idIncidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registra_Acidente1`
    FOREIGN KEY (`Acidente_idAcidente`)
    REFERENCES `Trabalho_Seguro`.`Acidente` (`idAcidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registra_Desvio1`
    FOREIGN KEY (`Desvio_idDesvio`)
    REFERENCES `Trabalho_Seguro`.`Desvio` (`idDesvio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registra_Funcionario1`
    FOREIGN KEY (`Funcionario_id_funcionario`)
    REFERENCES `Trabalho_Seguro`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Tem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Tem` (
  `EPI_idEPI` INT NOT NULL,
  `Funcao_idFuncao` INT NOT NULL,
  PRIMARY KEY (`EPI_idEPI`, `Funcao_idFuncao`),
  INDEX `fk_EPI_has_Funcao_Funcao1_idx` (`Funcao_idFuncao` ),
  INDEX `fk_EPI_has_Funcao_EPI1_idx` (`EPI_idEPI` ),
  CONSTRAINT `fk_EPI_has_Funcao_EPI1`
    FOREIGN KEY (`EPI_idEPI`)
    REFERENCES `Trabalho_Seguro`.`EPI` (`idEPI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EPI_has_Funcao_Funcao1`
    FOREIGN KEY (`Funcao_idFuncao`)
    REFERENCES `Trabalho_Seguro`.`Funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Treinamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Treinamento` (
  `idTreinamento` INT NOT NULL,
  `treinamento` VARCHAR(45) NOT NULL,
  `inicio` DATE NULL,
  `conclusao` DATE NULL,
  `validade` DATE NULL,
  `descricao` TEXT(1000) NULL,
  PRIMARY KEY (`idTreinamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`treinamento_Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`treinamento_Setor` (
  `Setor_idSetor` INT NOT NULL,
  `Treinamento_idTreinamento` INT NOT NULL,
  `Funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`Setor_idSetor`, `Treinamento_idTreinamento`),
  INDEX `fk_Setor_has_Treinamento_Treinamento1_idx` (`Treinamento_idTreinamento` ),
  INDEX `fk_Setor_has_Treinamento_Setor1_idx` (`Setor_idSetor` ),
  INDEX `fk_treinamento_Setor_Funcionario1_idx` (`Funcionario_id_funcionario` ),
  CONSTRAINT `fk_Setor_has_Treinamento_Setor1`
    FOREIGN KEY (`Setor_idSetor`)
    REFERENCES `Trabalho_Seguro`.`Setor` (`idSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Setor_has_Treinamento_Treinamento1`
    FOREIGN KEY (`Treinamento_idTreinamento`)
    REFERENCES `Trabalho_Seguro`.`Treinamento` (`idTreinamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_treinamento_Setor_Funcionario1`
    FOREIGN KEY (`Funcionario_id_funcionario`)
    REFERENCES `Trabalho_Seguro`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Cadastro` (
  `idCadastro` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `celular` VARCHAR(12) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `confirmar_senha` VARCHAR(45) NOT NULL,
  `genero` JSON NOT NULL,
  PRIMARY KEY (`idCadastro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Login` (
  `idLogin` INT NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  `Cadastro_idCadastro` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_Cadastro1_idx` (`Cadastro_idCadastro` ),
  CONSTRAINT `fk_Login_Cadastro1`
    FOREIGN KEY (`Cadastro_idCadastro`)
    REFERENCES `Trabalho_Seguro`.`Cadastro` (`idCadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Avaliacao_site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Avaliacao_site` (
  `idAvaliacao` INT NOT NULL,
  `estrela` JSON NULL,
  `opiniao` TEXT(1000) NULL,
  `melhoras` TEXT(1000) NULL,
  PRIMARY KEY (`idAvaliacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Identificar_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Identificar_avaliacao` (
  `Login_site_idLogin` INT NOT NULL,
  `Avaliacao_site_idAvaliacao` INT NOT NULL,
  PRIMARY KEY (`Login_site_idLogin`, `Avaliacao_site_idAvaliacao`),
  INDEX `fk_Login_site_has_Avaliacao_site_Avaliacao_site1_idx` (`Avaliacao_site_idAvaliacao` ),
  INDEX `fk_Login_site_has_Avaliacao_site_Login_site1_idx` (`Login_site_idLogin` ),
  CONSTRAINT `fk_Login_site_has_Avaliacao_site_Login_site1`
    FOREIGN KEY (`Login_site_idLogin`)
    REFERENCES `Trabalho_Seguro`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Login_site_has_Avaliacao_site_Avaliacao_site1`
    FOREIGN KEY (`Avaliacao_site_idAvaliacao`)
    REFERENCES `Trabalho_Seguro`.`Avaliacao_site` (`idAvaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Cadastro_Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Cadastro_Empresa` (
  `idCadastro_Empresa` INT NOT NULL,
  `nome_empresa` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(14) NOT NULL,
  `setor_atuacao` VARCHAR(45) NOT NULL,
  `tamanho_empresa` JSON NOT NULL,
  `Login_idLogin` INT NOT NULL,
  PRIMARY KEY (`idCadastro_Empresa`, `Login_idLogin`),
  INDEX `fk_Cadastro_Empresa_Login1_idx` (`Login_idLogin` ),
  CONSTRAINT `fk_Cadastro_Empresa_Login1`
    FOREIGN KEY (`Login_idLogin`)
    REFERENCES `Trabalho_Seguro`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `titular_cartao` VARCHAR(45) NOT NULL,
  `numero_cartao` VARCHAR(16) NOT NULL,
  `validade` DATE NOT NULL,
  `CVV` VARCHAR(3) NOT NULL,
  `logradouro` VARCHAR(45) NULL,
  `CEP` VARCHAR(10) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `plano_escolhido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Responsavel` (
  `Setor_idSetor` INT NOT NULL,
  `Funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`Setor_idSetor`, `Funcionario_id_funcionario`),
  INDEX `fk_Setor_has_Funcionario_Funcionario1_idx` (`Funcionario_id_funcionario` ),
  INDEX `fk_Setor_has_Funcionario_Setor1_idx` (`Setor_idSetor` ),
  CONSTRAINT `fk_Setor_has_Funcionario_Setor1`
    FOREIGN KEY (`Setor_idSetor`)
    REFERENCES `Trabalho_Seguro`.`Setor` (`idSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Setor_has_Funcionario_Funcionario1`
    FOREIGN KEY (`Funcionario_id_funcionario`)
    REFERENCES `Trabalho_Seguro`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Pagamento_Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Pagamento_Empresa` (
  `Pagamento_idPagamento` INT NOT NULL,
  `Cadastro_Empresa_idCadastro_Empresa` INT NOT NULL,
  PRIMARY KEY (`Pagamento_idPagamento`, `Cadastro_Empresa_idCadastro_Empresa`),
  INDEX `fk_Pagamento_has_Cadastro_Empresa_Cadastro_Empresa1_idx` (`Cadastro_Empresa_idCadastro_Empresa` ),
  INDEX `fk_Pagamento_has_Cadastro_Empresa_Pagamento1_idx` (`Pagamento_idPagamento` ),
  CONSTRAINT `fk_Pagamento_has_Cadastro_Empresa_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `Trabalho_Seguro`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_has_Cadastro_Empresa_Cadastro_Empresa1`
    FOREIGN KEY (`Cadastro_Empresa_idCadastro_Empresa`)
    REFERENCES `Trabalho_Seguro`.`Cadastro_Empresa` (`idCadastro_Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Seguro`.`Contem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Seguro`.`Contem` (
  `idContem` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `Funcionario_id_funcionario` INT NOT NULL,
  `EPI_idEPI` INT NOT NULL,
  PRIMARY KEY (`idContem`),
  INDEX `fk_Contem_Funcionario1_idx` (`Funcionario_id_funcionario` ),
  INDEX `fk_Contem_EPI1_idx` (`EPI_idEPI` ),
  CONSTRAINT `fk_Contem_Funcionario1`
    FOREIGN KEY (`Funcionario_id_funcionario`)
    REFERENCES `Trabalho_Seguro`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contem_EPI1`
    FOREIGN KEY (`EPI_idEPI`)
    REFERENCES `Trabalho_Seguro`.`EPI` (`idEPI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
